version: '3'

services:
  nodejs:
    build: ./ops/docker/nodejs
    container_name: "nodejs"
    expose:
      - 9050
    volumes:
      - .:/var/www/billing-data-collector
    networks:
      - training-network
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=user
      - MONGODB_PASS=secret
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - training-network

networks:
  training-network: ~
